export const GET_ALL_BLOGS_REQUEST = "GET_ALL_BLOGS_REQUEST"
export const GET_ALL_BLOGS_SUCCESS = "GET_ALL_BLOGS_SUCCESS"
export const GET_ALL_BLOGS_FAIL = "GET_ALL_BLOGS_FAIL"

export const GET_SINGLE_BLOGS_REQUEST = "GET_SINGLE_BLOGS_REQUEST"
export const GET_SINGLE_BLOGS_SUCCESS = "GET_SINGLE_BLOGS_SUCCESS"
export const GET_SINGLE_BLOGS_FAIL = "GET_SINGLE_BLOGS_FAIL"

export const ADD_BLOG_REQUEST = "ADD_BLOG_REQUEST"
export const ADD_BLOG_SUCCESS = "ADD_BLOG_SUCCESS"
export const ADD_BLOG_FAIL = "ADD_BLOG_FAIL"

export const UPDATE_BLOG_REQUEST = "UPDATE_BLOG_REQUEST"
export const UPDATE_BLOG_SUCCESS = "UPDATE_BLOG_SUCCESS"
export const UPDATE_BLOG_FAIL = "UPDATE_BLOG_FAIL"

export const DELETE_BLOG_REQUEST = "DELETE_BLOG_REQUEST"
export const DELETE_BLOG_SUCCESS = "DELETE_BLOG_SUCCESS"
export const DELETE_BLOG_FAIL = "DELETE_BLOG_FAIL"

export const GET_USER_BLOG_REQUEST = "GET_USER_BLOG_REQUEST"
export const GET_USER_BLOG_SUCCESS = "GET_USER_BLOG_SUCCESS"
export const GET_USER_BLOG_FAIL = "GET_USER_BLOG_FAIL"